AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Disable some overly strict cops for this Estonian ID library
Metrics/MethodLength:
  Max: 50  # Some methods handle complex authentication flows

Metrics/ClassLength:
  Max: 250 # CertificateReader needs comprehensive PKCS#11 functionality

Metrics/AbcSize:
  Max: 65  # Certificate parsing and authentication are inherently complex

Metrics/CyclomaticComplexity:
  Max: 15  # Estonian ID cards require complex logic

Metrics/PerceivedComplexity:
  Max: 15  # Same as above

# Allow longer lines for documentation and examples
Layout/LineLength:
  Max: 125

# Allow multiple empty lines for better organization in long files
Layout/EmptyLines:
  Enabled: false

# Relax some cops for hardware integration testing
Lint/SuppressedException:
  Enabled: false

# Allow predicate methods that aren't boolean for card connections
Naming/PredicateMethod:
  Enabled: false

# Allow private class methods for PKCS#11 singleton
Lint/IneffectiveAccessModifier:
  Enabled: false

# Allow unused method arguments in placeholder implementations
Lint/UnusedMethodArgument:
  Enabled: false

# Allow duplicate branch body in error handling
Lint/DuplicateBranch:
  Enabled: false

# Allow redundant else in complex conditionals
Style/EmptyElse:
  Enabled: false
